layout_spectrum: 0.7194463438354433
typography_spectrum: 0.6466413589660078
color:
  brandColors:
    - '#1A1F2B'
    - '#30395C'
    - '#4A6491'
    - '#85A5CC'
    - '#D0E4F2'
  brandStrength: 0.062365290243178606
  lightness: 0.576863280730322
  saturation: 0.776278164004907
  rhythmicContrast: 0.40838650334626436
opengraph:
  image: null
  type: null
  appId: null
analytics:
  google: null
  facebook: null
  twitter: null
name: SKYLAR
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: SKYLAR
description: designer luxury tech
purpose: []
