name: SKYLAR
favicon: null
layout_spectrum: 0.7194463438354433
typography_spectrum: 0.6466413589660078
title: SKYLAR
description: designer luxury tech
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#222222'
    - '#b3b4b6'
    - '#e6eaeb'
    - '#707173'
    - '#454746'
  brandStrength: 1
  lightness: 1
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
