typography_spectrum: 0.24270647205412388
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.22501995344646275
  lightness: 0.926828371360898
  saturation: 0.6057212415616959
  rhythmicContrast: 0.2583924059290439
opengraph:
  image: null
  type: null
  appId: null
layout_spectrum: 0.8376217999029905
analytics:
  google: null
  facebook: null
  twitter: null
name: Skylar
cta:
  domain: null
  bucket: null
  version: null
favicon: null
title: SKYLAR
purpose: []
